export enum Role {
  SOFTWARE_ARCHITECT = "SOFTWARE_ARCHITECT",
  LEAD_DEVELOPER = "LEAD_DEVELOPER",
  SENIOR_DEVELOPER = "SENIOR_DEVELOPER",
  DEVELOPER = "DEVELOPER",
  JUNIOR_DEVELOPER = "JUNIOR_DEVELOPER",
}
